spring:
  security:
    oauth2:
      client:
        registration:
          logingov:
            client-id: urn:gov:gsa:openidconnect.profiles:sp:sso:NOAA:onestop_user_api_localhost
            client-secret:
            authorization-grant-type: authorization_code
            redirect-uri-template: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            scope: openid+email
        provider:
          logingov:
            authorization-uri: https://idp.int.identitysandbox.gov/openid_connect/authorize
            token-uri: https://idp.int.identitysandbox.gov/api/openid_connect/token
            user-info-uri: https://idp.int.identitysandbox.gov/api/openid_connect/userinfo
            user-name-attribute: sub
            jwk-set-uri: https://idp.int.identitysandbox.gov/api/openid_connect/certs